// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change Execute_xD_Instruction.tt instead.

namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
        private int Execute_DD_Instruction()
        {
            Inc_R();
            var secondOpcodeByte = processorAgent.PeekNextOpcode();

            if (secondOpcodeByte == 0xCB)
            {
                Inc_R();
                processorAgent.FetchNextOpcode();
                var offset = processorAgent.FetchNextOpcode();
                return DDCB_InstructionExecutors[processorAgent.FetchNextOpcode()](offset);
            }

            if (DD_InstructionExecutors.TryGetValue(secondOpcodeByte, out var value))
            {
                Inc_R();
                processorAgent.FetchNextOpcode();
                return value();
            }

            return NOP();
        }

        private int Execute_FD_Instruction()
        {
            Inc_R();
            var secondOpcodeByte = processorAgent.PeekNextOpcode();

            if (secondOpcodeByte == 0xCB)
            {
                Inc_R();
                processorAgent.FetchNextOpcode();
                var offset = processorAgent.FetchNextOpcode();
                return FDCB_InstructionExecutors[processorAgent.FetchNextOpcode()](offset);
            }

            if (FD_InstructionExecutors.TryGetValue(secondOpcodeByte, out var value))
            {
                Inc_R();
                processorAgent.FetchNextOpcode();
                return value();
            }

            return NOP();
        }
    }
}