// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "IM n            .tt" instead.

namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
        /// <summary>
        /// The IM 0 instruction.
        /// </summary>
        private byte IM_0()
        {
            FetchFinished();

            processorAgent.SetInterruptMode(0);

            return 8;
        }

        /// <summary>
        /// The IM 1 instruction.
        /// </summary>
        private byte IM_1()
        {
            FetchFinished();

            processorAgent.SetInterruptMode(1);

            return 8;
        }

        /// <summary>
        /// The IM 2 instruction.
        /// </summary>
        private byte IM_2()
        {
            FetchFinished();

            processorAgent.SetInterruptMode(2);

            return 8;
        }
    }
}