// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "INC rr +        .tt" instead.

namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
        /// <summary>
        /// The INC BC instruction.
        /// </summary>
        private byte INC_BC()
        {
            FetchFinished();
            Registers.BC++;
            return 6;
        }

        /// <summary>
        /// The DEC BC instruction.
        /// </summary>
        private byte DEC_BC()
        {
            FetchFinished();
            Registers.BC--;
            return 6;
        }

        /// <summary>
        /// The INC DE instruction.
        /// </summary>
        private byte INC_DE()
        {
            FetchFinished();
            Registers.DE++;
            return 6;
        }

        /// <summary>
        /// The DEC DE instruction.
        /// </summary>
        private byte DEC_DE()
        {
            FetchFinished();
            Registers.DE--;
            return 6;
        }

        /// <summary>
        /// The INC HL instruction.
        /// </summary>
        private byte INC_HL()
        {
            FetchFinished();
            Registers.HL++;
            return 6;
        }

        /// <summary>
        /// The DEC HL instruction.
        /// </summary>
        private byte DEC_HL()
        {
            FetchFinished();
            Registers.HL--;
            return 6;
        }

        /// <summary>
        /// The INC SP instruction.
        /// </summary>
        private byte INC_SP()
        {
            FetchFinished();
            Registers.SP++;
            return 6;
        }

        /// <summary>
        /// The DEC SP instruction.
        /// </summary>
        private byte DEC_SP()
        {
            FetchFinished();
            Registers.SP--;
            return 6;
        }

        /// <summary>
        /// The INC IX instruction.
        /// </summary>
        private byte INC_IX()
        {
            FetchFinished();
            Registers.IX++;
            return 10;
        }

        /// <summary>
        /// The DEC IX instruction.
        /// </summary>
        private byte DEC_IX()
        {
            FetchFinished();
            Registers.IX--;
            return 10;
        }

        /// <summary>
        /// The INC IY instruction.
        /// </summary>
        private byte INC_IY()
        {
            FetchFinished();
            Registers.IY++;
            return 10;
        }

        /// <summary>
        /// The DEC IY instruction.
        /// </summary>
        private byte DEC_IY()
        {
            FetchFinished();
            Registers.IY--;
            return 10;
        }
    }
}