
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © Kaalenco Software. All Rights Reserved")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyCompany("Kaalenco")]
[assembly: AssemblyProduct("Z80-asm-dasm")]

internal static class BuildInfo
{
	public static DateTime Date = new DateTime(2024, 12, 09, 10, 50, 26, DateTimeKind.Utc);
}
	